apiVersion: ENC[AES256_GCM,data:32Q=,iv:3VWWpC3/tkYwzFneaxJfHjK2oNzqY7EXEzdQmW8ERAE=,tag:XFJUeqxWCFuK3tvgJmjiVQ==,type:str]
kind: ENC[AES256_GCM,data:DWuJip0l,iv:lsxUtRSFNrhFj8KcKWqNbqDtYw4yXau7FffMXPUgt1s=,tag:wy790UQPZIu1Lqq/1VX+pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e3JwNhAR5Vc/fg==,iv:0i+35JjnPV3Nq9J27+DVMWS15Lq0FJ2MC5QLlGEk9wM=,tag:FKzq+TcItlmh+KnwSu85zg==,type:str]
type: ENC[AES256_GCM,data:KrekLX7J,iv:YFyvYHKs1agJL4djPA29h06EsH5JJa/ffJ3+QH6nE+E=,tag:lnix4jit9+DizNBelAzlow==,type:str]
data:
    TELE_TOKEN: null
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-386217/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-07-04T19:17:29Z"
          enc: CiQAQ/ehTPW9mlPPGwICjzan33si3OVjKf/ZKMa7u6FnUE7bfZgSSQCFkYYTFHi3m5iczkbMG2pfJjTLp1kZSgb6KfHChFloF0eAvlOD0n7AmRjl/Tm4g0ERJGL5vVgwHNx8Fbvax9hrV52MG+06tB8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-04T19:17:30Z"
    mac: ENC[AES256_GCM,data:GXXfJtDmIJhx3tyWRu4VVQ5Z/OHCfgy1O/FIy6c/RLYz+gnes9euekd602phm8g5VJTa56NWcAhiVZ6oOcELTwJg0zL7BPZkKXlYjq/SI9WdqcgmJPEiPDYs0kggzYyoUUHWzAR+gyO6Mt2YAZoOVjW0RxBh2b2lu4ES3L8rkQw=,iv:JtRvE0A+F4tlw4enzzF53CzKMU7Gt/3VwgKbbCyik6k=,tag:B/RftAm1Jn2k0Dl1XG73ow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
