apiVersion: ENC[AES256_GCM,data:kBU=,iv:a6Qjf86Vrym5lwS359nVlyGVX/YhAxhJf28KQv9RPD0=,tag:EpwXWiwBfSC34Hph8CTXuA==,type:str]
kind: ENC[AES256_GCM,data:GYL4u2On,iv:qjf/EF2rKl0qXHb/zkEuHaxcwfaRuwg0gAN0YQyzOjU=,tag:QhgljVdAPFPdYQD0JqBcmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ib8ojpFEXu2jXQ==,iv:p/qbjufd8CKVVncjL9Zn/Fwu0qorpuvapc9PpDMberU=,tag:9/VjrxJQZBUhGSGeeRP5hA==,type:str]
type: ENC[AES256_GCM,data:TqmDWjRY,iv:O8W9plNZYwdqLvdUzaI8NSEv+Sj08kQH84eNYJ4mG9Q=,tag:WBVs4+qxAXRF238F40VVDw==,type:str]
data:
    TELE_TOKEN: null
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-386217/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-07-04T17:07:39Z"
          enc: CiQAQ/ehTNERFcE7S60GMKYH39+0GHggGU4fKZYeV/EARsj0758SSQCFkYYTgbYHe36sOGiOezZHgVspElayrg93RjrCs7giUMlViFTFAYnKNseqpUSe5Abg3WAKdIh4pRHqFEn7Qrch5XSYdHloaTE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-04T17:07:40Z"
    mac: ENC[AES256_GCM,data:GXJ1xqbFHjJ4glvlZIiz4iHs6FC4Xw1l/FVthgFcRCVei1Dbx1DoHDO5DpejzkOaSKNQrnAsc4ah5JBX/0yUxVSZNljIYZvi4N2MN78Pp8N/tMyqjOUvmFadcVo6sdqGYfkjkZFD83Sb1phtZPcEf4B/RgeQ0LoPiKV4rPbJYd0=,iv:Bdk/3lNYTsdzpcj1/B7gb8g2Sfd6gY5Ah7HkUKaOpWw=,tag:ukrFKHU9ZVwnd5r3hgajdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
