name: KBOT-CICD

on: push

jobs: 
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test 
        run: make test
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME}}
        run: make image push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    
      - name: Install sops
        run: |
          curl -L -o /usr/local/bin/sops https://github.com/getsops/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          chmod +x /usr/local/bin/sops
    
      - name: Generate Kubernetes Secret Manifest
        run: |
          echo "apiVersion: v1
          kind: Secret
          metadata:
            name: kbot-token
          type: Opaque
          data:
            TELE_TOKEN: $(echo -n '${{ secrets.TELE_TOKEN }}' | base64)" > secret-manifest.yaml
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: Encrypt Kubernetes Secret Manifest
        run: |
          sops --encrypt --gcp-kms projects/k8s-k3s-386217/locations/global/keyRings/sops/cryptoKeys/sops-key secret-manifest.yaml > secret-manifest.enc.yaml
    
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        id: install

      - name: Configure kubectl with cluster credentials
        run: |
          gcloud container clusters get-credentials main --zone us-central1-c --project k8s-k3s-386217
          export KUBECONFIG=$HOME/.kube/config

      - name: Check GKE plugin installation
        run: |
          if ! gke-gcloud-auth-plugin --version; then
            gcloud components install gke-gcloud-auth-plugin
          fi

      - name: Apply Kubernetes Secret Manifest
        run: |
          kubectl apply -f secret-manifest.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git commit -am "update version $VERSION"
          git push

      - name: Set up SSH to commit and push secret
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.FLUX_OPS_KEY }}
        run: |
          git clone git@github.com:ng-n/flux-gitops.git
          cd flux-gitops
          mkdir -p clusters/dev
          cp secret-manifest.enc.yaml clusters/dev/secret-manifest.enc.yaml
          git add clusters/dev/secret-enc.yaml
          git commit -m "add encrypted secret"
          git push origin main