name: KBOT-CICD

# Triggers the workflow to run when a push event occurs in the repository.
on: 
  push:
    branches:
      - develop

jobs:
  # Continuous Integration 
  ci:
    name: CI
    runs-on: ubuntu-latest

    # Checks out repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
    # Runs tests
      - name: Run test 
        run: make test
    
    # Logs in DockerHub
    #  - name: Docker Hub login
    #    uses: docker/login-action@v1
    #    with:
    #      username: ${{ secrets.DOCKERHUB_USERNAME }}
    #      password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Logs in Github Container Registry
      - name: GHCR login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN}}

    # Buld&Push
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME}}
        run: make image push

  # Continuous Delivery
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
    # Updates the '.image.X' fields in the 'helm/values.yaml with the value of VERSION, TARGETOS and TARGETARCH'
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION)' -i '.image.os=linux' -i '.image.arch=amd64' helm/values.yaml
    
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push